name: Build
run-name: SQL dacpac-Datei erzeugen
on:
  workflow_dispatch:

jobs:
  Build-Latest-SQL:
    runs-on: windows-latest

    steps:
      - name: Initialisierung
        run: 'echo Workflow gestartet. Ref-Name: ${{ github.ref_name }}.'

      - name: Repository abrufen
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Paket erzeugen
        run: msbuild -property:Configuration=Release
        working-directory: ${{ github.workspace }}\Latest

      - name: Ausgabe anzeigen
        run: ls
        working-directory: ${{ github.workspace }}/Latest/bin/Release
