name: Build
run-name: SQL dacpac-Datei erzeugen
on:
  workflow_dispatch:

jobs:
  Build-Latest-SQL:
    runs-on: ubuntu-latest

    steps:
      - name: Initialisierung
        run: 'echo Workflow gestartet. Ref-Name: ${{ github.ref_name }}.'

      - name: Repository abrufen
        uses: actions/checkout@v4

      - name: Dotnet installieren
        uses: actions/setup-dotnet@v4

      - name: SqlPackage installieren
        run: dotnet tool install -g microsoft.sqlpackage

      - name: Workspace Inhalt anzeigen
        run: tree
        working-directory: ${{ github.workspace }}

      - name: Paket erzeugen
        run: dotnet build
        working-directory: ${{ github.workspace }}/Latest

      - name: Ausgabe anzeigen
        run: ls
        working-directory: ${{ github.workspace }}/Latest/bin/Release
