name: Build
run-name: SQL dacpac-Datei erzeugen
on:
  release:
    types: [published]

jobs:
  Build-Latest-SQL:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Initialisierung
        run: 'echo Workflow gestartet. Ref-Name: ${{ github.ref_name }}.'

      - name: Repository abrufen
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Paket erzeugen SQL2022
        run: msbuild -property:Configuration=Release
        working-directory: ${{ github.workspace }}\Latest

      - name: Ausgabe anzeigen
        run: ls
        working-directory: ${{ github.workspace }}\Latest\bin\Release

      - name: DACPAC im Release ablegen
        run: gh release upload ${{ github.ref_name }} *.dacpac
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ github.workspace }}\Latest\bin\Release

      - name: Paket erzeugen SQL2019
        run: msbuild -property:Configuration=Release
        working-directory: ${{ github.workspace }}\SQL2019

      - name: Ausgabe anzeigen
        run: ls
        working-directory: ${{ github.workspace }}\SQL2019\bin\Release

      - name: DACPAC im Release ablegen
        run: gh release upload ${{ github.ref_name }} *.dacpac
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ github.workspace }}\SQL2019\bin\Release

      - name: Paket erzeugen SQL2017
        run: msbuild -property:Configuration=Release
        working-directory: ${{ github.workspace }}\SQL2017

      - name: Ausgabe anzeigen
        run: ls
        working-directory: ${{ github.workspace }}\SQL2017\bin\Release

      - name: DACPAC im Release ablegen
        run: gh release upload ${{ github.ref_name }} *.dacpac
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ github.workspace }}\SQL2017\bin\Release